version: 2
updates:
  # npm依存関係の更新
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    reviewers:
      - "takurot"
    assignees:
      - "takurot"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    ignore:
      # eslint-plugin-jest v29+ は @typescript-eslint v8+ が必要で
      # 現在の react-scripts 5.0.1 と互換性がない
      - dependency-name: "eslint-plugin-jest"
        versions: [">=29.0.0"]
      # TypeScript ESLint v8+ は破壊的変更が多く、
      # react-scripts のアップデートが必要
      - dependency-name: "@typescript-eslint/*"
        versions: [">=8.0.0"]
      # TypeScript v5+ は react-scripts 5.0.1 と互換性がない
      # react-scripts は "^3.2.1 || ^4" のみサポート
      - dependency-name: "typescript"
        versions: [">=5.0.0"]
      # React v19+ は破壊的変更が多く、慎重な検証が必要
      # 全体的なエコシステムアップデートが必要
      - dependency-name: "react"
        versions: [">=19.0.0"]
      - dependency-name: "react-dom"
        versions: [">=19.0.0"]
      - dependency-name: "@types/react"
        versions: [">=19.0.0"]
      - dependency-name: "@types/react-dom"
        versions: [">=19.0.0"]
      # MUI v7+ は破壊的変更があり、段階的アップデートが必要
      # @mui/icons-material とバージョン同期が必要
      - dependency-name: "@mui/material"
        versions: [">=7.0.0"]
      - dependency-name: "@mui/icons-material"
        versions: [">=7.0.0"]
      # eslint-plugin-jest v28+ は @typescript-eslint v6+ を要求
      # 現在は v5.62.0 を使用しているため互換性がない
      - dependency-name: "eslint-plugin-jest"
        versions: [">=28.0.0"]
      # web-vitals v5+ は破壊的変更が多い
      # getFID()関数削除、ReportHandler型変更など
      - dependency-name: "web-vitals"
        versions: [">=5.0.0"]
    
  # GitHub Actions ワークフローの更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "takurot"
    assignees:
      - "takurot"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions" 